http://localhost:3000/posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FjaGluIiwiaWF0IjoxNjQ2MDUyMzU1fQ.Yo1EFbIz5UlsPDzqCyme5dhCljpHjRLEkIoHgIuYets

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "Sachin"
}
